import { Link } from "@tanstack/react-router";
import { ArrowRight, MapPin, CalendarDays, Scale, Banknote, SearchX } from "lucide-react";
import kinnowCrates from "@/assets/lot-kinnow-crates.jpg";
import kinnowOrchard from "@/assets/lot-kinnow-orchard.jpg";
import mosambiImg from "@/assets/lot-mosambi.jpg";
import lemonImg from "@/assets/lot-lemon.jpg";
import logoAsset from "@/assets/kinnowlink-logo.jpg.asset.json";
import type { ButtonHTMLAttributes, ReactNode } from "react";
import type { Lot, Requirement, Status } from "@/lib/marketplace";

export function Brand({compact=false}:{compact?:boolean}){ return <Link to="/" className="brand" aria-label="KinnowLink home"><span className="brand-mark"><img src={logoAsset.url} alt="" width={compact?20:25} height={compact?20:25}/></span><span>Kinnow<span>Link</span></span></Link> }
export function DemoNote({children="Changes are saved on this device for this demo."}:{children?:ReactNode}){return <div className="demo-note"><span/> {children}</div>}
export function StatusBadge({status}:{status:string}){return <span className={`status status-${status.toLowerCase()}`}>{status}</span>}
export function Button({variant="primary",className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger"}){return <button className={`button button-${variant} ${className}`} {...props}/>}
export function EmptyState({title,copy,action}:{title:string;copy:string;action?:ReactNode}){return <div className="empty"><SearchX/><h3>{title}</h3><p>{copy}</p>{action}</div>}
export function PageHeader({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy?:string;action?:ReactNode}){return <header className="page-header"><div className="min-w-0"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{action&&<div className="shrink-0">{action}</div>}</header>}
export function Field({label,required,children,hint}:{label:string;required?:boolean;children:ReactNode;hint?:string}){return <label className="field"><span>{label}{required&&<b> *</b>}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function lotImage(lot:Lot){const v=lot.variety.toLowerCase();if(v.includes("mosambi"))return mosambiImg;if(v.includes("lemon"))return lemonImg;return lot.id.length%2?kinnowOrchard:kinnowCrates;}
export function LotCard({lot,actions}:{lot:Lot;actions?:ReactNode}){return <article className="listing-card"><img className="lot-cover" src={lotImage(lot)} alt={`${lot.variety} lot from ${lot.grower}`} loading="lazy" width={1024} height={640}/><div className="listing-top"><div><p className="eyebrow">LOT · {lot.id.toUpperCase()}</p><h3>{lot.variety}</h3><p className="party">by {lot.grower}</p></div><StatusBadge status={lot.status}/></div><div className="facts"><span><Scale/>{lot.quantity} {lot.unit}</span><span><span className="grade-dot"/>{lot.grade}</span><span><MapPin/>{lot.location}</span><span><CalendarDays/>{formatDate(lot.date)}</span><span><Banknote/>{lot.price?`PKR ${lot.price.toLocaleString()}/t`:"Open to offers"}</span></div><p className="description">{lot.description}</p>{actions&&<div className="card-actions">{actions}</div>}</article>}
export function RequirementCard({item,actions}:{item:Requirement;actions?:ReactNode}){return <article className="listing-card requirement"><div className="listing-top"><div><p className="eyebrow">NEED · {item.id.toUpperCase()}</p><h3>{item.variety}</h3><p className="party">by {item.buyer}</p></div><StatusBadge status={item.status}/></div><div className="facts"><span><Scale/>{item.quantity} {item.unit}</span><span><span className="grade-dot"/>{item.grade}</span><span><MapPin/>{item.location}</span><span><CalendarDays/>By {formatDate(item.date)}</span><span><Banknote/>{item.price?`Up to PKR ${item.price.toLocaleString()}/t`:"Open to offers"}</span></div><p className="description">{item.description}</p>{actions&&<div className="card-actions">{actions}</div>}</article>}
export function LinkButton({to,children,variant="primary"}:{to:string;children:ReactNode;variant?:"primary"|"secondary"|"ghost"}){return <Link to={to} className={`button button-${variant}`}>{children}<ArrowRight size={16}/></Link>}
export const formatDate=(value:string)=>new Intl.DateTimeFormat("en-PK",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`));
export const nextStatus=(status:Status):Status=>status==="Active"?"Paused":status==="Paused"?"Active":"Active";